FROM ruby:3.1-bullseye

RUN set -eux ;\
    DEBIAN_FRONTEND=noninteractive apt-get update ;\
    DEBIAN_FRONTEND=noninteractive apt-get install  -y --no-install-recommends \
        sqlite3 \
        sqlite3-pcre

WORKDIR /code

RUN gem install puma

RUN git clone https://github.com/taginfo/taginfo.git && \
    cd taginfo && \
    bundle install
