FROM ruby:3.3-bookworm

RUN set -eux ;\
    DEBIAN_FRONTEND=noninteractive apt-get update ;\
    DEBIAN_FRONTEND=noninteractive apt-get install  -y --no-install-recommends \
        sqlite3 \
        sqlite3-pcre

WORKDIR /code

RUN gem install puma

RUN git clone https://github.com/taginfo/taginfo.git && \
    cd taginfo && \
    bundle install

COPY indoorequal.svg taginfo/web/public/img/logo
RUN sed -i s/c\ =\ @config/c\ =\ @config.dup/ /code/taginfo/web/lib/config.rb

EXPOSE 4567
